version: '3.5'
services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - "8080:3000"
    volumes:
      - ${PROJECTFOLDER}:/var/project

networks:
  default:
    name: internal
    external: true